name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file DockerfileBuild --tag demowebbuild:latest
    - name: Test Docker image
      run: |
        docker run -d --name demowebbuild-test demowebbuild:latest /bin/sh -c "echo 'Image running successfully!'"
        sleep 10
        docker stop demowebbuild-test
        docker rm demowebbuild-test
