name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file DockerfileBuild --tag demowebbuild:latest
    - name: Test Docker image
      run: |
            docker run -d --name demowebbuild-test -p 8080:8080 demowebbuild:latest
            sleep 60 # Wait for the application to start
            curl -f http://localhost:8080/actuator/health || (echo "Health check failed" && exit 1)
            docker stop demowebbuild-test
            docker rm demowebbuild-test
