name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag demowebbuild:$(date +%s)
    - name: Test Docker image
      run: |
        docker run --rm demowebbuild /bin/sh -c "echo 'Image built successfully!'"
